### PR TITLE
Add vdiff.el support

### PR DESCRIPTION
**Pull request by edkolev**
Refs #70

Please let me know if I can improve the PR.

Maybe the `evil-collection-delete-operators` var should be in evil-collection.el

### CODE REVIEW

**Comment by edkolev** [comment]
> Maybe the evil-collection-delete-operators var should be in evil-collection.el

I just moved it there - CI (package-lint in particular) complained.

**Comment by jojojames** [comment]
I don't use vdiff myself so I can merge this and if someone has more tweaks/feedback, we can iterate on it as it comes.

As for the delete operators, I'll check to see if I can move it to vdiff when I have some time. It's not bad where it is though.

**Comment by noctuid** [comment]
Looks good to me. As for the `evil-collection-delete-operators`, it could potentially be removed in the future if these packages bound `[remap evil-delete]` enstead of `d` itself. This is what lispyville does now. If there were any new alternate delete operators added like this, it would be possible to have them work without adding them to `evil-collection-delete-operators`. For example:

```elisp
(when (or (eq evil-this-operator (key-binding [remap evil-delete]))
          (memq evil-this-operator evil-collection-delete-operators))
  #'vdiff-receive-changes)
```
At this point, this is probably overkill, but it may be worth considering in the future to prevent having to keep track of every delete operator.

**Comment by jojojames** [comment]
^ Sounds good, I'll give it a shot.

@edkolev 

Should this be 'evil' instead in evil-collection-delete-operators?

```
-                                           vil-sp-delete
+                                           evil-sp-delete
```

**Comment by edkolev** [comment]
@jojojames thanks, I just submitted a fix.

**Pull request merged**
