### PR TITLE
Normalize mark bindings

### PR DESCRIPTION
**Pull request by Ambrevar**
Now that we've covered a decent number of modes, I've skimmed through them to see which bindings prevailed for marking.
It turns out that their was little deviation, so I've adjusted the few modes that showed inconsistencies.

(I might have missed a few, though.)

I've updated the rationale accordingly.  Let me know what you think.

### CODE REVIEW

**Comment by Ambrevar** [comment]
Regarding @jojojames last suggestion in #19, the main question that remains is whether we should replace `x` for `#` to execute action on mark.

**Comment by maxsandova** [comment]
I think that `#` it is way out of reach and most of people who come from vanilla emacs are accustomed to use `x`.

**Comment by Ambrevar** [comment]
On a QWERTY keyboard, `#` is fairly easy to press with `Shift-3`.

**Comment by jojojames** [comment]
Might be good to check the CI and see what can fix it up.

Looks good otherwise!

For 'execute mark', I think leaving it on 'x' is probably OK unless 'x' is taken by some deletion operation. We can probably backfill to '#' if so.

**Comment by Ambrevar** [comment]
CI should be fine now.

**Comment by Ambrevar** [comment]
Merged.

**Pull request closed without merging**
